### ISSUE TITLE
Kaartjes mogen in een rij komen te staan

### ISSUE THREAD

**Issue by Amber-vdr** [r20222/connect-your-tribe-squad-page#11]
Je hebt nu een geheel overzicht van de gehele squad, misschien een idee om het in een rij van 4 te laten zien. Meteen de gehele squad laten zien kan overweldigend overkomen omdat je meteen alle content krijgt te zien. 4 personen laten zien geeft een kalmere en betere overzicht waardoor alles makkelijker te lezen is.

**Comment by r20222** [comment]
Yess goede tip, ik heb nu steeds 3 op een rij 👍
