### ISSUE TITLE
Wrap your buttons in a container.

### ISSUE THREAD

**Issue by Siem-P** [r20222/connect-your-tribe-squad-page#12]
For example 

<div class="button-container">
    <button></button>
</div>

https://github.com/r20222/connect-your-tribe-squad-page/blob/236070d8ca33ea53fb6e224d82733feac8468ccf/views/index.ejs#L12-L38

**Comment by r20222** [comment]
Yes, ik heb het nu iets netter uitgelijnd door grid te gebruiken ipv flexbox 👍
