### ISSUE TITLE
Kijk naar de semantiek van je HTML. 

### ISSUE THREAD

**Issue by Siem-P** [r20222/connect-your-tribe-squad-page#6]
Je kan een HTML validator doen om een beter inzicht te krijgen van waar je je headings plaatst.

**Comment by r20222** [comment]
Yes, ik heb de problemen die ik kreeg opgelost, heb vooral veel onnodige trailing slashes bij de img weggehaald: 

https://github.com/r20222/connect-your-tribe-squad-page/blob/8fafe629c3ba8e196a04709df57cb3410b358823/views/gamen.ejs#L15
