### ISSUE TITLE
Ruimte tussen button en header

### ISSUE THREAD

**Issue by ghost** [r20222/connect-your-tribe-squad-page#9]
Kijk of je misschien de witruitme hetzelfde kan maken tussen de heading en de articles en de button en articles.

Er zit nu namelijk meer ruimte tussen de button onderaan de pagina en de articles.

**Comment by r20222** [comment]
Goed gezien, ik heb het nu opgelost door de onderste button helemaal weg te halen en van FDND een link te maken die teruggaat naar de homepage.
